### ISSUE TITLE
Necessary?

### ISSUE THREAD

**Issue by trentgoing** [hrnyc30-supernova/supernova-retail-app#83]
https://github.com/hrnyc30-supernova/project-greenfield/blob/5ac0391184c8f19d692bc4c9784c8eba82dc2892/src/components/questions-and-answers/questionsAndAnswers.js#L14-L24

Opinion: These functions don't add much clarity for me.  It is probably worth just invoking the useState callback within your JSX.

**Comment by cam1403** [comment]
@trentgoing done!
