### ISSUE TITLE
Standardize variable names

### ISSUE THREAD

**Issue by trentgoing** [hrnyc30-supernova/supernova-retail-app#84]
https://github.com/hrnyc30-supernova/project-greenfield/blob/5ac0391184c8f19d692bc4c9784c8eba82dc2892/src/components/questions-and-answers/questionsAndAnswers.js#L11-L12

I believe both of these are controlling the appearance of a Modal.  If that is the case, it helps to standardize naming conventions.  AddAnswer => AddAnswerModal.   Or, something even more descriptive: isAddAnswerModalOpen

**Comment by cam1403** [comment]
@trentgoing Changed variable names!
