### ISSUE TITLE
I don't actually know...

### ISSUE THREAD

**Issue by trentgoing** [hrnyc30-supernova/supernova-retail-app#85]
https://github.com/hrnyc30-supernova/project-greenfield/blob/5ac0391184c8f19d692bc4c9784c8eba82dc2892/src/components/questions-and-answers/questionsAndAnswers.js#L37

But based on similar patterns, defining this type of 'root' is ideally done as close to the root application as possible.   Every time this Q&A component is updated, I'd expect the root to be regenerated.   This might be a bit interesting as it might be re-initializing the recoil state each time.  Even though you're accessing the recoil data further down the App tree, it might be best to put this in your app component, which would remain constant as you navigate from page to page.   Unless, of course, you want to just re-create recoil new on each page.    

Again, I've never worked with it before, but happy to discuss further.  Especially if you've been noticing some interesting state behavior.

**Comment by cam1403** [comment]
@trentgoing originally I would have just done it at the root application, but didn't want to interfere with anybody's code since I was the only one utilizing it (even though It probably wouldn't have hurt their code )

**Comment by cam1403** [comment]
Moved the root tag to index, and everything still works the same
