### ISSUE TITLE
Testing is awesome!

### ISSUE THREAD

**Issue by trentgoing** [hrnyc30-supernova/supernova-retail-app#86]
https://github.com/hrnyc30-supernova/project-greenfield/blob/5ac0391184c8f19d692bc4c9784c8eba82dc2892/src/components/questions-and-answers/questionDisplay.test.js#L9

Glad you have it initialized.  The hard part will be testing interaction and state in addition to renders!  Keep going with more elaborate tests!

**Comment by cam1403** [comment]
Will do!
