### ISSUE TITLE
Lots of conditions for a single action

### ISSUE THREAD

**Issue by trentgoing** [hrnyc30-supernova/supernova-retail-app#88]
https://github.com/hrnyc30-supernova/project-greenfield/blob/5ac0391184c8f19d692bc4c9784c8eba82dc2892/src/components/ratings-and-reviews/ratingsReviews.js#L22

This line makes me curious about the circumstance when product id would be the same but the name would change, or another variant of that.

**Comment by cam1403** [comment]
yessss trent yess!! @trentgoing

**Comment by sconnoll** [comment]
Thank you, I was able to reduce it to just the first one because that's the only piece of data that relates to the api call being made. It now says

if (prevProps.currentProductID !== this.props.currentProductID) {
  //make api call
}
