### ISSUE TITLE
Destructure

### ISSUE THREAD

**Issue by trentgoing** [hrnyc30-supernova/supernova-retail-app#90]
https://github.com/hrnyc30-supernova/project-greenfield/blob/5ac0391184c8f19d692bc4c9784c8eba82dc2892/src/components/ratings-and-reviews/ratingsBreakdown.js#L5-L16

You can clean up a bit more by destructuring props into the properties needed, avoiding `props.` in the function

**Comment by sconnoll** [comment]
Destructuring is helpful here and a good idea to keep in mind for all functional components, thanks
