### ISSUE TITLE
Curious about combining

### ISSUE THREAD

**Issue by trentgoing** [hrnyc30-supernova/supernova-retail-app#91]
https://github.com/hrnyc30-supernova/project-greenfield/blob/5ac0391184c8f19d692bc4c9784c8eba82dc2892/src/components/ratings-and-reviews/ratingFilters.js#L81

I can't immediately tell why this component is created twice, but then conditionally renders 2 different widgets.   Could this be broken into two different components?

**Comment by sconnoll** [comment]
Yes, it definitely can be. Both 'scales' seemed to use a lot of the same logic, so I put them together, but it makes more sense to have them separated. This is completed, thanks!
